# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_auto_20160511_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='user_id',
            new_name='user',
        ),
    ]
